add product.html
ilovemath25/E-Bookstore pull request #15
Opened 2024-11-27 11:36 UTC by thkyaw

2024-11-27 13:23 UTC, ilovemath25 requested changes

2024-11-27 13:23 UTC, ilovemath25 commented on ebookstore_flask/static/image/book.jpg
bro, 用png比較好
用jpg會花位子
然後可以的話不要用白色background，就是全圖只有書而已，沒有白色background

2024-11-28 04:15 UTC, ilovemath25 requested changes

2024-11-28 04:15 UTC, ilovemath25 commented on ebookstore_flask/routes/product.py
> +def index():
應該名字不要用index因為index函數代表首頁面，用其他名字吧。

2024-11-28 07:39 UTC, ilovemath25 requested changes

2024-11-28 07:39 UTC, ilovemath25 commented on ebookstore_flask/templates/product.html
> +               <span><strong>Category:</strong> Fiction</span></br></br>
少一個span

2024-11-28 07:39 UTC, ilovemath25 commented on ebookstore_flask/templates/product.html
> +               <span><strong>Sales Count:</strong> <span id="sales">150</span></span>
81到83的外面tag用div比較好我感覺
所以br一個就好了
然後改`</br>`變成`<br>`

2024-11-28 14:54 UTC, thkyaw commented on ebookstore_flask/templates/product.html
> +               <div><strong>Category:</strong><span id="category">Fiction</div><br>
done

2024-11-28 15:00 UTC, ilovemath25 approved these changes

2024-11-28 15:00 UTC, merged